### ISSUE TITLE
Problem while handling option tags with empty values

### ISSUE THREAD

**Issue by gcosta** [unitedstates/contact-congress#608]
I just created the script for Zoe Lofgren, but for some reason the option tags on her forms don't have values, they are simply:

``` html
<select name="required-prefix" required="required">
                            <option></option>
                            <option>Mr.</option>
                            <option>Mrs.</option>
                            <option>Ms.</option>
                            <option>Dr.</option>
                            <option>Rev.</option>
</select>
```

So apparently this causes the scraper to be unable to get any options for the select, and even if I add them by hand (or try to send a hardcoded value), I get failures like this:

```
Unable to find css "option[value=\"Mr.\"]"
["/home/congressforms/congress-forms/app/models/congress_member.rb:45:in `rescue in fill_out_form'", "/home/congressforms/congress-forms/app/models/congress_member.rb:39:in `fill_out_form'", "/home/congressforms/congress-forms/app/helpers/form_fill_handler.rb:15:in `block in create_thread'"]
```

**Comment by lucyq7** [comment]
YMAL file not found. I am working on it.
