### ISSUE TITLE
No implicit conversion of Symbol into String

### ISSUE THREAD

**Issue by akosednar** [unitedstates/contact-congress#695]
I think this may be an issue with the tester? Appears with the YAML of #91  and #690

```
 no implicit conversion of Symbol into String
["/home/congressforms/congress-forms/app/models/congress_member.rb:44:in `include?'", "/home/congressforms/congress-forms/app/models/congress_member.rb:44:in `rescue in fill_out_form'", "/home/congressforms/congress-forms/app/models/congress_member.rb:39:in `fill_out_form'", "/home/congressforms/congress-forms/app/helpers/form_fill_handler.rb:15:in `block in create_thread'"]
```

**Comment by lucyq7** [comment]
YMAL file not found. I am working on it.
